# Generated by Django 3.1.5 on 2026-04-19 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research_procedures', '0014_notification_schema_restructure'),
        ('research_procedures', '0014_notification_complete_schema'),
        ('research_procedures', '0015_notification_final_schema'),
    ]

    operations = [
    ]
